[package]
name = "s_curve"
version = "0.1.0"
edition = "2021"

[dependencies]
gnuplot = { version = "0.0.44", optional = true }
num-traits = { version = "0.2", default-features = false, features = ["libm"] }

[features]
default = ["std", "plot"]
std = []
plot = ["dep:gnuplot"]
