[package]
name = "s_curve"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
gnuplot = "0.0.44"
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
